Repository MSA-Logistics-service/backend, pull requests merged in 2024-09, with the labels that each got.

#6 Logistics 서비스 Resilience4j 및 서킷브레이커 의존성 설정
  logistics/build.gradle
  logistics/src/main/resources/application.yml
Labels: feat

#33 주문 생성 (배송 생성 api 호출) 구현
  logistics/src/main/java/msa/logistics/service/logistics/common/exception/ErrorCode.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/dto/DeliveryCreateRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/controller/OrderController.java
  logistics/src/main/java/msa/logistics/service/logistics/order/domain/Order.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/request/OrderCreateRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/request/OrderUpdateRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/response/OrderResponseDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/repository/OrderRepository.java
  logistics/src/main/java/msa/logistics/service/logistics/order/service/OrderService.java
Labels: feat

#32 Auth 서버 구현
  auth/.gitignore
  auth/build.gradle
  auth/gradle/wrapper/gradle-wrapper.jar
  auth/gradle/wrapper/gradle-wrapper.properties
  auth/gradlew
  auth/gradlew.bat
  auth/settings.gradle
  auth/src/main/java/msa/logistics/service/auth/AuthApplication.java
  auth/src/main/java/msa/logistics/service/auth/client/UserServiceClient.java
  auth/src/main/java/msa/logistics/service/auth/config/webSecurityConfig.java
  auth/src/main/java/msa/logistics/service/auth/controller/AuthController.java
  auth/src/main/java/msa/logistics/service/auth/domain/User.java
  auth/src/main/java/msa/logistics/service/auth/dto/LoginRequestDto.java
  auth/src/main/java/msa/logistics/service/auth/dto/LoginResponseDto.java
  auth/src/main/java/msa/logistics/service/auth/dto/UserDto.java
  auth/src/main/java/msa/logistics/service/auth/security/UserDetailsImpl.java
  auth/src/main/java/msa/logistics/service/auth/security/UserDetailsServiceImpl.java
  auth/src/main/java/msa/logistics/service/auth/util/JwtUtil.java
  auth/src/main/resources/application-dev.yml
  auth/src/main/resources/application.yml
  auth/src/test/java/msa/logistics/service/auth/AuthApplicationTests.java
Labels: feat

#36 refactor : 주문 로직 리팩토링
  logistics/src/main/java/msa/logistics/service/logistics/delivery/domain/Delivery.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/domain/DeliveryRoute.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/domain/DeliveryStatus.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/domain/RouteStatus.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/dto/DeliveryEditRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/dto/DeliveryRouteEditRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/delivery/service/DeliveryService.java
  logistics/src/main/java/msa/logistics/service/logistics/order/domain/Order.java
  logistics/src/main/java/msa/logistics/service/logistics/order/service/OrderService.java
Labels: refactor

#38 Order 조회, 수정, 삭제 구현
  logistics/src/main/java/msa/logistics/service/logistics/order/controller/OrderController.java
  logistics/src/main/java/msa/logistics/service/logistics/order/domain/Order.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/response/OrderResponseDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/repository/OrderRepository.java
  logistics/src/main/java/msa/logistics/service/logistics/order/service/OrderService.java
Labels: feat

#39 Product, Order 주문 생성 시 재고 차감 로직 구현
  logistics/src/main/java/msa/logistics/service/logistics/common/exception/ErrorCode.java
  logistics/src/main/java/msa/logistics/service/logistics/order/domain/Order.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/request/OrderCreateRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/request/OrderUpdateRequestDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/response/OrderResponseDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/service/OrderService.java
  logistics/src/main/java/msa/logistics/service/logistics/product/domain/Product.java
Labels: refactor

#43 상품 설명 추천 ai 응답 받기 기능 구현
  logistics/src/main/java/msa/logistics/service/logistics/product/controller/ProductAiController.java
  logistics/src/main/java/msa/logistics/service/logistics/product/domain/ProductAiChat.java
  logistics/src/main/java/msa/logistics/service/logistics/product/repository/ProductAiRepository.java
  logistics/src/main/java/msa/logistics/service/logistics/product/service/ProductAiService.java
  logistics/src/main/resources/application.yml
Labels: feat

#45 Hub
  hub/src/main/java/com/msa/hub/hub/controller/HubController.java
  hub/src/main/java/com/msa/hub/hub/domain/Hub.java
  hub/src/main/java/com/msa/hub/hub/dto/HubRequestDto.java
  hub/src/main/java/com/msa/hub/hub/dto/HubResponseDto.java
  hub/src/main/java/com/msa/hub/hub/repository/HubRepository.java
  hub/src/main/java/com/msa/hub/hub/service/HubService.java
  hub/src/main/java/com/msa/hub/hubPath/controller/HubPathController.java
  hub/src/main/java/com/msa/hub/hubPath/domain/HubPath.java
  hub/src/main/java/com/msa/hub/hubPath/dto/HubPathRequestDto.java
  hub/src/main/java/com/msa/hub/hubPath/dto/HubPathResponseDto.java
  hub/src/main/java/com/msa/hub/hubPath/repository/HubPathRepository.java
  hub/src/main/java/com/msa/hub/hubPath/service/HubPathService.java
  hub/src/main/java/com/msa/hub/vendor/controller/VendorController.java
  hub/src/main/java/com/msa/hub/vendor/domain/Vendor.java
  hub/src/main/java/com/msa/hub/vendor/domain/VendorType.java
  hub/src/main/java/com/msa/hub/vendor/service/VendorService.java
  hub/src/main/resources/application.properties
  hub/src/main/resources/application.yml
Labels: feat

#47 feat: #13 hub 서비스 db 연동을 위한 docker-compose.yml 파일 수정
  docker-compose.yml
  postgres-init/hubs/init.sql
Labels: feat

#54 Logistic 인증/인가 설정 구현
  logistics/build.gradle
  logistics/src/main/java/msa/logistics/service/logistics/common/config/AuditAwareImpl.java
  logistics/src/main/java/msa/logistics/service/logistics/common/config/JpaConfig.java
  logistics/src/main/java/msa/logistics/service/logistics/config/SecurityConfig.java
  logistics/src/main/java/msa/logistics/service/logistics/filter/CustomPreAuthFilter.java
Labels: feat

#56 hub
  hub/src/main/java/com/msa/hub/HubApplication.java
  hub/src/main/java/com/msa/hub/hub/controller/HubController.java
  hub/src/main/java/com/msa/hub/hub/domain/Hub.java
  hub/src/main/java/com/msa/hub/hub/service/HubService.java
  hub/src/main/java/com/msa/hub/hubPath/controller/HubPathController.java
  hub/src/main/java/com/msa/hub/hubPath/domain/HubPath.java
  hub/src/main/java/com/msa/hub/hubPath/dto/HubPathResponseDto.java
  hub/src/main/java/com/msa/hub/hubPath/repository/HubPathRepository.java
  hub/src/main/java/com/msa/hub/hubPath/service/HubPathService.java
  hub/src/main/java/com/msa/hub/vendor/controller/VendorController.java
  hub/src/main/java/com/msa/hub/vendor/domain/Vendor.java
  hub/src/main/java/com/msa/hub/vendor/dto/VendorRequestDto.java
  hub/src/main/java/com/msa/hub/vendor/dto/VendorResponseDto.java
  hub/src/main/java/com/msa/hub/vendor/service/VendorService.java
Labels: fix

#57 Order, Product 쪽 FeignClient 리팩토링 완료
  gateway/src/main/resources/application.yml
  logistics/src/main/java/msa/logistics/service/logistics/config/SecurityConfig.java
  logistics/src/main/java/msa/logistics/service/logistics/order/service/OrderService.java
  logistics/src/main/java/msa/logistics/service/logistics/product/controller/ProductAiController.java
  logistics/src/main/java/msa/logistics/service/logistics/product/domain/ProductAiChat.java
  logistics/src/main/java/msa/logistics/service/logistics/product/service/ProductAiService.java
Labels: refactor

#58 Logistic refactor (인증/인가)
  logistics/src/main/java/msa/logistics/service/logistics/common/exception/GlobalExceptionHandler.java
  logistics/src/main/java/msa/logistics/service/logistics/order/controller/OrderController.java
  logistics/src/main/java/msa/logistics/service/logistics/order/service/OrderService.java
  logistics/src/main/java/msa/logistics/service/logistics/product/controller/ProductController.java
  logistics/src/main/java/msa/logistics/service/logistics/product/service/ProductService.java
Labels: refactor

#60 Logistic refactor
  logistics/src/main/java/msa/logistics/service/logistics/order/controller/OrderController.java
Labels: refactor

#63 hub
  hub/src/main/java/com/msa/hub/hub/controller/HubController.java
  hub/src/main/java/com/msa/hub/hub/service/HubService.java
  hub/src/main/java/com/msa/hub/hubPath/controller/HubPathController.java
  hub/src/main/java/com/msa/hub/hubPath/service/HubPathService.java
Labels: fix

#65 Logistics 서킷 브레이커 Fallback 로직 작성
  logistics/src/main/java/msa/logistics/service/logistics/client/fallback/HubFallback.java
  logistics/src/main/java/msa/logistics/service/logistics/client/fallback/HubFallbackFactory.java
  logistics/src/main/java/msa/logistics/service/logistics/client/hub/HubClient.java
  logistics/src/main/java/msa/logistics/service/logistics/client/hub/HubService.java
  logistics/src/main/java/msa/logistics/service/logistics/client/hub/dto/HubResponseDto.java
  logistics/src/main/java/msa/logistics/service/logistics/client/vendor/dto/VendorResponseDto.java
  logistics/src/main/java/msa/logistics/service/logistics/order/dto/request/OrderCreateRequestDto.java
Labels: feat

#66 refactor: #2 Logistics 애플리케이션 공통 설정과 개발 환경 설정 파일 분리
  logistics/src/main/resources/application-dev.yml
  logistics/src/main/resources/application.yml
Labels: refactor

#67 hub
  README.md
  infra.png
  systems design.png
  t.jpg
Labels: docs

#69 프로메테우스, 그라파나 연동
  docker-compose.yml
  gateway/src/main/java/msa/logistics/service/gateway/config/SecurityConfig.java
  gateway/src/main/resources/application.yml
  logistics/src/main/java/msa/logistics/service/logistics/config/SecurityConfig.java
  logistics/src/main/resources/application.yml
  prometheus/prometheus.yml
Labels: feat
